config/routes.rb
Rails.application.routes.draw do
  resources :trainings
  resources :anschreibens
  resources :lebenslaufs
  resources :jobs
  resources :cvs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'jobs#index'
  get 'about', to: 'welcome#about'

  resources :articles

  get 'signup', to: "users#new"
  resources :users, except: [:new]
  get 'login', to: "sessions#new"
  post 'login', to: "sessions#create"
  delete 'logout', to: "sessions#destroy"

  resources :categories, except: [:destroy]
end

app/models/training.rb
class Training < ApplicationRecord
  JOB_TYPES = ["Bau,HandWerk & Produktion", "Büroarbeit & Verwaltung",
   "Gastronomie & Tourismus", "Kundenservice & Callcenter",
   "Sozieler Sektor", "Transport, Logiskit", "Vertrieb & Verkauf", "Weitere Jobs" ]
end

app/controllers/trainings_controller.rb
class TrainingsController < ApplicationController
  before_action :set_training, only: %i[ show edit update destroy ]

  # GET /trainings or /trainings.json
  def index
     if(params.has_key?(:job_type))
      @trainings = Training.where(job_type: params[:job_type]).order("created_at asc")
    else
      @trainings = Training.all.order("created_at asc")
    end
  end


  # GET /trainings/1 or /trainings/1.json
  def show
  end

  # GET /trainings/new
  def new
    @training = Training.new
  end

  # GET /trainings/1/edit
  def edit
  end

  # POST /trainings or /trainings.json
  def create
    @training = Training.new(training_params)

    respond_to do |format|
      if @training.save
        format.html { redirect_to @training, notice: "Training was successfully created." }
        format.json { render :show, status: :created, location: @training }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @training.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trainings/1 or /trainings/1.json
  def update
    respond_to do |format|
      if @training.update(training_params)
        format.html { redirect_to @training, notice: "Training was successfully updated." }
        format.json { render :show, status: :ok, location: @training }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @training.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trainings/1 or /trainings/1.json
  def destroy
    @training.destroy
    respond_to do |format|
      format.html { redirect_to trainings_url, notice: "Training was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_training
      @training = Training.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def training_params
      params.require(:training).permit(:frage, :antwort, :job_type)
    end
end

app/helpers/trainings_helper.rb
module TrainingsHelper
end

app/views/trainings/_form.html.erb
<h1 style="text-align: center;">Geben Sie ein Frage und passenede Antwort</h1>
<%= form_with(model: training, local: true) do |form| %>
  <% if training.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(training.errors.count, "error") %> prohibited this training from being saved:</h2>

      <ul>
      <% training.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="row">
  <div class="column" style="width: 100%">
  <div class="field">
    <label>Geben Sie Die Frage im Vorstellungsgespräch ein</label>
    <%= form.text_area :frage, id: :training_frage, placeholder: 'Welches Karriereziel haben Sie vor Augen?' %>
  </div>

  <div class="field">
    <label>Geben Sie die Antwort ein</label>
    <%= form.text_area :antwort, id: :training_antwort, placeholder: 'Auf diese Frage die richtige Antwort zu finden, ist...' %>
  </div>

 <div class="field">
    <label>Vorstellungsgespräch Training Category</label><br>
    <span class="select">
              <%= form.select :job_type, collection: Training::JOB_TYPES, prompt: "Select a job type" %>
            </span>
  </div><br>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div>
</div>

app/views/trainings/_panel.html.erb
<style>
  .cards-list {
  z-index: 0;
  width: 100%;
  display: flex;
  justify-content: space-around;
  flex-wrap: wrap;
  background: #0000001c;


}

.card_p {
  margin: 10px auto;
  width: 23%;
  height: 25px;
  /*border-radius: 40px;*/
  cursor: pointer;
  transition: 0.4s;
}
 .cards-list1 {
  z-index: 0;
  width: 100%;
  display: flex;
  justify-content: space-around;
  flex-wrap: wrap;

}

.card_all {
  margin: 10px auto;
  width: 48%;
  height: 39px;
  /*border-radius: 40px;*/
  cursor: pointer;
  transition: 0.4s;
}
/*.card:hover {
  transform: scale(0.9, 0.9);
  box-shadow: 5px 5px 30px 15px rgba(0,0,0,0.25),
    -5px -5px 30px 15px rgba(0,0,0,0.22);
}
*/

.card_p a, .card_all a  {
    color: black;
    cursor: pointer;
    text-decoration: none;
    font-size: 16px;
    font-weight: bold;
}
.btn {
    width: 100%;
    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
    background-color: #f1f1f1;
   }
   /*#5bc0de* inof color */

btn:hover {
   background-color:orangered ;
  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
}
.card_p a:hover {
  color: white;
}
.card_all a:hover {
  color: white;
}

@media all and (max-width: 500px) {
  .card-list {
    /* On small screens, we are no longer using row direction but column */
    flex-direction: column;
  }
}

@media screen and (max-width: 600px) {
  .card_p {
    /* On small screens, we are no longer using row direction but column */
    width: 49%;
  }
}
@media screen and (max-width: 600px) {
  .card_p a {
    /* On small screens, we are no longer using row direction but column */
    font-size: 14px;
  }
}
@media (min-width: 1200px) {
.container {
    width: 98%;
}
}

</style>


<div class="cards-list1">
  <div class="card_all" style="width: 60%;, margin-right: 30%">
    <%= link_to 'All Vorstellungsgespräch Trainings', trainings_path, class: 'btn btn-info', id: 'all' %>
  </div>
</div>
<div class="cards-list">
  <div class="card_p">
    <%= link_to 'Bau,HandWerk & Produktion', trainings_path(job_type: "Bau,HandWerk & Produktion"), class: 'btn btn-info' %>
</div>


  <div class="card_p">
     <%= link_to 'Büroarbeit & Verwaltung', trainings_path(job_type: "Büroarbeit & Verwaltung"), class: 'btn btn-info' %>
  </div>

    <div class="card_p">
     <%= link_to 'Gastronomie & Tourismus', trainings_path(job_type: "Gastronomie & Tourismus"), class: 'btn btn-info' %>
  </div>

  <div class="card_p">
    <%= link_to 'Kundenservice & Callcenter', trainings_path(job_type: "Kundenservice & Callcenter"), class: 'btn btn-info'  %>
  </div>
</div>

<div class="cards-list">
  <div class="card_p">
    <%= link_to 'Sozieler Sektor', trainings_path(job_type: "Sozieler Sektor"), class: 'btn btn-info' %>
  </div>

  <div class="card_p">
    <%= link_to 'Transport, Logiskit', trainings_path(job_type: "Transport, Logiskit"), class: 'btn btn-info' %>
  </div>

  <div class="card_p">
    <%= link_to 'Vertrieb & Verkauf', trainings_path(job_type: "Vertrieb & Verkauf"), class: 'btn btn-info' %>
  </div>

  <div class="card_p">
     <%= link_to 'Weitere Jobs', trainings_path(job_type: "Weitere Jobs"), class: 'btn btn-info' %>
  </div>
</div>

app/views/trainings/edit.html.erb
<h1>Editing Training</h1>

<%= render 'form', training: @training %>

<%= link_to 'Show', @training %> |
<%= link_to 'Back', trainings_path %>

app/views/trainings/index.html.erb
<%= render 'panel' %>
<p id="notice"><%= notice %></p>

    <% @trainings.each do |training| %>
    <div class="center">
      <h3> <%= training.frage %></h3>
      <p><%= training.antwort %></p>
      <h6> <%= training.job_type %> </h6>


       <%#= link_to 'Show', training %>


       <%= link_to 'Edit', edit_training_path(training) %>
       <%= link_to 'Destroy', training, method: :delete, data: { confirm: 'Are you sure?' } %>
       </div>
    <% end %>

<br>

<%= link_to 'New Training', new_training_path %>
<br>
<br>
<br>

app/views/trainings/new.html.erb
<%= render 'form', training: @training %>

<%= link_to 'Back', trainings_path %>

app/views/trainings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Frage:</strong>
  <%= @training.frage %>
</p>

<p>
  <strong>Antwort:</strong>
  <%= @training.antwort %>
</p>

<p>
  <strong>Job type:</strong>
  <%= @training.job_type %>
</p>

<%= link_to 'Edit', edit_training_path(@training) %> |
<%= link_to 'Back', trainings_path %>