config/routes.rb
Rails.application.routes.draw do
  resources :trainings
  resources :anschreibens
  resources :lebenslaufs
  resources :jobs
  resources :cvs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'jobs#index'
  get 'about', to: 'welcome#about'

  resources :articles

  get 'signup', to: "users#new"
  resources :users, except: [:new]
  get 'login', to: "sessions#new"
  post 'login', to: "sessions#create"
  delete 'logout', to: "sessions#destroy"

  resources :categories, except: [:destroy]
end

app/models/lebenslauf.rb
class Lebenslauf < ApplicationRecord
  mount_uploader :avatar, AvatarUploader
end

app/controllers/lebenslaufs_controller.rb
class LebenslaufsController < ApplicationController
  before_action :set_lebenslauf, only: [:show, :edit, :update, :destroy]

  # GET /lebenslaufs
  # GET /lebenslaufs.json
  def index
    @lebenslaufs = Lebenslauf.all
  end

  # GET /lebenslaufs/1
  # GET /lebenslaufs/1.json
  def show
      @lebenslauf = Lebenslauf.find(params[:id])
       respond_to do |format|
            format.html
            format.pdf do
                render pdf: "lebenslauf. #{@lebenslauf_params}",
                page_size: 'A4',
                template: "lebenslaufs/show.html.erb",
                layout: "pdf.html",
                lowquality: true,
                zoom: 1,
                dpi: 75
            end
        end
     end


  # GET /lebenslaufs/new
  def new
    @lebenslauf = Lebenslauf.new
  end

  # GET /lebenslaufs/1/edit
  def edit
  end

  # POST /lebenslaufs
  # POST /lebenslaufs.json
  def create
    @lebenslauf = Lebenslauf.new(lebenslauf_params)

    respond_to do |format|
      if @lebenslauf.save
        format.html { redirect_to @lebenslauf, notice: 'Lebenslauf was successfully created.' }
        format.json { render :show, status: :created, location: @lebenslauf }
      else
        format.html { render :new }
        format.json { render json: @lebenslauf.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lebenslaufs/1
  # PATCH/PUT /lebenslaufs/1.json
  def update
    respond_to do |format|
      if @lebenslauf.update(lebenslauf_params)
        format.html { redirect_to @lebenslauf, notice: 'Lebenslauf was successfully updated.' }
        format.json { render :show, status: :ok, location: @lebenslauf }
      else
        format.html { render :edit }
        format.json { render json: @lebenslauf.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lebenslaufs/1
  # DELETE /lebenslaufs/1.json
  def destroy
    @lebenslauf.destroy
    respond_to do |format|
      format.html { redirect_to lebenslaufs_url, notice: 'Lebenslauf was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lebenslauf
      @lebenslauf = Lebenslauf.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lebenslauf_params
      params.require(:lebenslauf).permit(:name, :avatar, :address, :city, :postcode, :phone, :email, :birth, :nationality, :facebook, :linkedin, :degree, :uni, :grade, :year, :degree1, :uni1, :grade1, :year1, :degree2, :uni2, :grade2, :year2, :degree3, :uni3, :grade3, :year3, :degree4, :uni4, :grade4, :year4, :degree5, :uni5, :grade5, :year5, :company, :jobtitle, :start, :end, :detail, :company1, :jobtitle1, :start1, :end1, :detail1, :company2, :jobtitle2, :start2, :end2, :detail2, :company3, :jobtitle3, :start3, :end3, :detail3, :skill, :skill1, :skill2, :skill3, :skill4, :skill5, :skill6, :skill7, :language, :niveau, :language1, :niveau1, :language2, :niveau2, :language3, :niveau3)
    end
end

app/helpers/lebenslaufs_helper.rb
module LebenslaufsHelper
end

app/views/lebenslaufs/edit.html.erb
<h1>Editing Lebenslauf</h1>

<%= render 'form', lebenslauf: @lebenslauf %>

<%= link_to 'Show', @lebenslauf %> |
<%= link_to 'Back', lebenslaufs_path %>

app/views/lebenslaufs/index.html.erb
<!--
<p id="notice"><%= notice %></p>

<h1>Lebenslaufs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>City</th>
      <th>Postcode</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Birth</th>
      <th>Nationality</th>
      <th>Facebook</th>
      <th>Linkedin</th>
      <th>Degree</th>
      <th>Uni</th>
      <th>Grade</th>
      <th>Year</th>
      <th>Degree1</th>
      <th>Uni1</th>
      <th>Grade1</th>
      <th>Year1</th>
      <th>Degree2</th>
      <th>Uni2</th>
      <th>Grade2</th>
      <th>Year2</th>
      <th>Degree3</th>
      <th>Uni3</th>
      <th>Grade3</th>
      <th>Year3</th>
      <th>Degree4</th>
      <th>Uni4</th>
      <th>Grade4</th>
      <th>Year4</th>
      <th>Degree5</th>
      <th>Uni5</th>
      <th>Grade5</th>
      <th>Year5</th>
      <th>Company</th>
      <th>Jobtitle</th>
      <th>Start</th>
      <th>End</th>
      <th>Detail</th>
      <th>Company1</th>
      <th>Jobtitle1</th>
      <th>Start1</th>
      <th>End1</th>
      <th>Detail1</th>
      <th>Company2</th>
      <th>Jobtitle2</th>
      <th>Start2</th>
      <th>End2</th>
      <th>Detail2</th>
      <th>Company3</th>
      <th>Jobtitle3</th>
      <th>Start3</th>
      <th>End3</th>
      <th>Detail3</th>
      <th>Skill</th>
      <th>Skill1</th>
      <th>Skill2</th>
      <th>Skill3</th>
      <th>Skill4</th>
      <th>Skill5</th>
      <th>Skill6</th>
      <th>Skill7</th>
      <th>Language</th>
      <th>Niveau</th>
      <th>Language1</th>
      <th>Niveau1</th>
      <th>Language2</th>
      <th>Niveau2</th>
      <th>Language3</th>
      <th>Niveau3</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lebenslaufs.each do |lebenslauf| %>
      <tr>
        <td><%= lebenslauf.name %></td>
        <td><%= lebenslauf.address %></td>
        <td><%= lebenslauf.city %></td>
        <td><%= lebenslauf.postcode %></td>
        <td><%= lebenslauf.phone %></td>
        <td><%= lebenslauf.email %></td>
        <td><%= lebenslauf.birth %></td>
        <td><%= lebenslauf.nationality %></td>
        <td><%= lebenslauf.facebook %></td>
        <td><%= lebenslauf.linkedin %></td>
        <td><%= lebenslauf.degree %></td>
        <td><%= lebenslauf.uni %></td>
        <td><%= lebenslauf.grade %></td>
        <td><%= lebenslauf.year %></td>
        <td><%= lebenslauf.degree1 %></td>
        <td><%= lebenslauf.uni1 %></td>
        <td><%= lebenslauf.grade1 %></td>
        <td><%= lebenslauf.year1 %></td>
        <td><%= lebenslauf.degree2 %></td>
        <td><%= lebenslauf.uni2 %></td>
        <td><%= lebenslauf.grade2 %></td>
        <td><%= lebenslauf.year2 %></td>
        <td><%= lebenslauf.degree3 %></td>
        <td><%= lebenslauf.uni3 %></td>
        <td><%= lebenslauf.grade3 %></td>
        <td><%= lebenslauf.year3 %></td>
        <td><%= lebenslauf.degree4 %></td>
        <td><%= lebenslauf.uni4 %></td>
        <td><%= lebenslauf.grade4 %></td>
        <td><%= lebenslauf.year4 %></td>
        <td><%= lebenslauf.degree5 %></td>
        <td><%= lebenslauf.uni5 %></td>
        <td><%= lebenslauf.grade5 %></td>
        <td><%= lebenslauf.year5 %></td>
        <td><%= lebenslauf.company %></td>
        <td><%= lebenslauf.jobtitle %></td>
        <td><%= lebenslauf.start %></td>
        <td><%= lebenslauf.end %></td>
        <td><%= lebenslauf.detail %></td>
        <td><%= lebenslauf.company1 %></td>
        <td><%= lebenslauf.jobtitle1 %></td>
        <td><%= lebenslauf.start1 %></td>
        <td><%= lebenslauf.end1 %></td>
        <td><%= lebenslauf.detail1 %></td>
        <td><%= lebenslauf.company2 %></td>
        <td><%= lebenslauf.jobtitle2 %></td>
        <td><%= lebenslauf.start2 %></td>
        <td><%= lebenslauf.end2 %></td>
        <td><%= lebenslauf.detail2 %></td>
        <td><%= lebenslauf.company3 %></td>
        <td><%= lebenslauf.jobtitle3 %></td>
        <td><%= lebenslauf.start3 %></td>
        <td><%= lebenslauf.end3 %></td>
        <td><%= lebenslauf.detail3 %></td>
        <td><%= lebenslauf.skill %></td>
        <td><%= lebenslauf.skill1 %></td>
        <td><%= lebenslauf.skill2 %></td>
        <td><%= lebenslauf.skill3 %></td>
        <td><%= lebenslauf.skill4 %></td>
        <td><%= lebenslauf.skill5 %></td>
        <td><%= lebenslauf.skill6 %></td>
        <td><%= lebenslauf.skill7 %></td>
        <td><%= lebenslauf.language %></td>
        <td><%= lebenslauf.niveau %></td>
        <td><%= lebenslauf.language1 %></td>
        <td><%= lebenslauf.niveau1 %></td>
        <td><%= lebenslauf.language2 %></td>
        <td><%= lebenslauf.niveau2 %></td>
        <td><%= lebenslauf.language3 %></td>
        <td><%= lebenslauf.niveau3 %></td>
        <td><%= link_to 'Show', lebenslauf %></td>
        <td><%= link_to 'Edit', edit_lebenslauf_path(lebenslauf) %></td>
        <td><%= link_to 'Destroy', lebenslauf, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lebenslauf', new_lebenslauf_path %>
-->

app/views/lebenslaufs/new.html.erb
<%= render 'form', lebenslauf: @lebenslauf %>

<%#= link_to 'Back', lebenslaufs_path %>

app/views/lebenslaufs/show.html.erb
 <script src="pdf.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.9.2/html2pdf.bundle.js"></script>

    <div class="col-md-12 text-right mb-3">
                <button class="btn btn-primary" id="download"> download pdf</button>
            </div>
            <div class="card" id="invoice">
<div class="row">
  <div class="column" id="left" style="width: 30%">
     <div id="profile-pic"><% if !@lebenslauf.avatar.file.nil? %>
      <%= link_to image_tag(@lebenslauf.avatar_url, class: "has-text-centered") %>
    <% end %></div>
 <h3 style="background: white;">Persönlichen Daten</h3>
  <p><%= @lebenslauf.name %></p>
  <p><%= @lebenslauf.address %></p>
  <p><%= @lebenslauf.postcode %> <%= @lebenslauf.city %></p>
  <p><%= @lebenslauf.birth %></p>
  <p><%= @lebenslauf.nationality %></p>
  <h3 style="background: white;">Kontakte:</h3>
  <p><span id="span">Telefone: </span> <%= @lebenslauf.phone %></p>
  <p><span id="span">E-Mail: </span>  <%= @lebenslauf.email %></p>
  <p><span id="span">Facebook:</span>  <%= @lebenslauf.facebook %></p>
  <p><span id="span">LinkedIn:</span> <%= @lebenslauf.linkedin %></p>

  <h3 style="background: white;">Kompetenzn:</h3>
  <p><%= @lebenslauf.skill %> </p>
  <p><%= @lebenslauf.skill1 %> </p>
  <p><%= @lebenslauf.skill2 %> </p>
  <p><%= @lebenslauf.skill3 %> </p>
  <p><%= @lebenslauf.skill4 %></p>
  <p><%= @lebenslauf.skill5 %></p>
  <p><%= @lebenslauf.skill6 %></p>
  <p><%= @lebenslauf.skill7 %></p>

  <h3 style="background: white;">Sprachen:</h3>
  <p><%= @lebenslauf.language %> <span><%= @lebenslauf.niveau %></span></p>

  <p><%= @lebenslauf.language1 %> <span><%= @lebenslauf.niveau1 %></span></p>

  <p><%= @lebenslauf.language2 %> <span><%= @lebenslauf.niveau2 %></span></p>

  <p><%= @lebenslauf.language3 %> <span><%= @lebenslauf.niveau3 %></span></p>


  </div>
   <div class="column" id="right" style="width: 70%">
  <div class="beruf">
    <h1 id="beruf"> Beruflichen Erfahrungen</h1>
    <h4 id="company-title"><%= @lebenslauf.jobtitle %></h4>
    <h4 id="company"><%= @lebenslauf.company %></h4>
    <h4 id="start" style="text-align:left;"> <%= @lebenslauf.start %> <strong>  </strong> <%= @lebenslauf.end %> </h4>
    <h4 id="detail" style="text-align:left;"> <%= @lebenslauf.detail %> </h4>
<br>
     <h4 id="company-title"><%= @lebenslauf.jobtitle1 %></h4>
    <h4 id="company"><%= @lebenslauf.company1 %></h4>
    <h4 id="start" style="text-align:left;"> <%= @lebenslauf.start1 %> <strong>  </strong> <%= @lebenslauf.end1 %> </h4>
    <h4 id="detail" style="text-align:left;"> <%= @lebenslauf.detail1 %> </h4>
    <br>
     <h4 id="company-title"><%= @lebenslauf.jobtitle2 %></h4>
    <h4 id="company"><%= @lebenslauf.company2 %></h4>
    <h4 id="start" style="text-align:left;"> <%= @lebenslauf.start2 %> <strong>  </strong> <%= @lebenslauf.end2 %> </h4>
    <h4 id="detail" style="text-align:left;"> <%= @lebenslauf.detail2 %> </h4>
    <br>
     <h4 id="company-title"><%= @lebenslauf.jobtitle3 %></h4>
    <h4 id="company"><%= @lebenslauf.company3 %></h4>
    <h4 id="start" style="text-align:left;"> <%= @lebenslauf.start3 %> <strong>  </strong> <%= @lebenslauf.end1 %> </h4>
    <h4 id="detail" style="text-align:left;"> <%= @lebenslauf.detail3 %> </h4>

  </div>
    <h1 id="bildung"> Bildung :</h1>
  <div class="education">
  <h4 id="degree" style="font-weight: bold;"><%= @lebenslauf.degree %></h4>

  <h5 id="degree"><%= @lebenslauf.uni %></h5>

  <h5 id="degree"><string> </string> <%= @lebenslauf.grade %></h5>

  <h5 id="degree"><strong> </strong> <%= @lebenslauf.year %></h5>
  <br>
  <h4 id="degree" style="font-weight: bold;" > <%= @lebenslauf.degree1 %></h4>

  <h5 id="degree"> <%= @lebenslauf.uni1 %></h5>

  <h5 id="degree"><string></string> <%= @lebenslauf.grade1 %></h5>

  <h5 id="degree"><strong> </strong> <%= @lebenslauf.year1 %></h5>
  <br>
  <h4 id="degree" style="font-weight: bold;" > <%= @lebenslauf.degree2 %></h4>

  <h5 id="degree"> <%= @lebenslauf.uni2 %></h5>

  <h5 id="degree"><string></string> <%= @lebenslauf.grade2 %></h5>

  <h5 id="degree"><strong></strong> <%= @lebenslauf.year2 %></h5>
  <br>
  </div>
  </div>
</div>
</div>
   <script>
      window.onload = function () {
    document.getElementById("download")
        .addEventListener("click", () => {
            const invoice = this.document.getElementById("invoice");
            console.log(invoice);
            console.log(window);
            var opt = {
                margin: 1,
                filename: 'myfile.pdf',
                image: { type: 'jpeg', quality: 0.98 },
                html2canvas: { scale: 2 },
                jsPDF: { unit: 'in', format: 'letter', orientation: 'portrait' }
            };
            html2pdf().from(invoice).set(opt).save();
        })
}
</script>