config/routes.rb
Rails.application.routes.draw do
  resources :trainings
  resources :anschreibens
  resources :lebenslaufs
  resources :jobs
  resources :cvs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'jobs#index'
  get 'about', to: 'welcome#about'

  resources :articles

  get 'signup', to: "users#new"
  resources :users, except: [:new]
  get 'login', to: "sessions#new"
  post 'login', to: "sessions#create"
  delete 'logout', to: "sessions#destroy"

  resources :categories, except: [:destroy]
end

app/models/anschreiben.rb
class Anschreiben < ApplicationRecord
  STELLE = ["Ausbildung", "Job", "Praktikum", "Studium"]
end

app/controllers/anschreibens_controller.rb
class AnschreibensController < ApplicationController
  before_action :set_anschreiben, only: %i[ show edit update destroy ]

  # GET /anschreibens or /anschreibens.json
  def index
    @anschreibens = Anschreiben.all
  end

  # GET /anschreibens/1 or /anschreibens/1.json
  def show
  end

  # GET /anschreibens/new
  def new
    @anschreiben = Anschreiben.new
  end

  # GET /anschreibens/1/edit
  def edit
  end

  # POST /anschreibens or /anschreibens.json
  def create
    @anschreiben = Anschreiben.new(anschreiben_params)

    respond_to do |format|
      if @anschreiben.save
        format.html { redirect_to @anschreiben, notice: "Anschreiben was successfully created." }
        format.json { render :show, status: :created, location: @anschreiben }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @anschreiben.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /anschreibens/1 or /anschreibens/1.json
  def update
    respond_to do |format|
      if @anschreiben.update(anschreiben_params)
        format.html { redirect_to @anschreiben, notice: "Anschreiben was successfully updated." }
        format.json { render :show, status: :ok, location: @anschreiben }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @anschreiben.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /anschreibens/1 or /anschreibens/1.json
  def destroy
    @anschreiben.destroy
    respond_to do |format|
      format.html { redirect_to anschreibens_url, notice: "Anschreiben was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_anschreiben
      @anschreiben = Anschreiben.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def anschreiben_params
      params.require(:anschreiben).permit(:name, :adess, :plz, :plzz, :city, :company_name, :comapay_adress, :company_city, :bewerbung, :stelle, :datum)
    end
end

app/helpers/anschreibens_helper.rb
module AnschreibensHelper
end

app/views/anschreibens/_form.html.erb
<style>
  .column {
    height: 450px;
  }
  h2 {
    text-align: center;
  }
  input[type=submit] {
  background-color:lightseagreen ;
  color: white;
  padding: 14px 20px;
  border: none;
  cursor: pointer;
  font-weight: bold;
  font-size: 17px;
}

input[type=submit]:hover {
  background-color: #1e90ffcf;
}
.actions {
  width: 40%;
  margin-left: auto;
  margin-right: auto;
}
</style>

<%= form_with(model: anschreiben, local: true) do |form| %>
  <% if anschreiben.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(anschreiben.errors.count, "error") %> prohibited this anschreiben from being saved:</h2>

      <ul>
      <% anschreiben.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h2> Geben Sie Ihre Daten ein um die Anschreiben zu haben.  </h2>
<div class="row">
  <div class="column">
  <div class="field">
    <label>Name:</label>
    <%= form.text_field :name, id: :anschreiben_name, placeholder: 'Ihren Name' %>
  </div>

  <div class="field">
    <label>Adess & Haus Nr</label>
    <%= form.text_field :adess, id: :anschreiben_adess, placeholder: 'Meller Str 17' %>
  </div>

  <div class="field">
   <label>PLZ</label>
    <%= form.text_field :plz, id: :anschreiben_plz, placeholder: '13404 etc'%>
  </div>

  <div class="field">
    <label>Stadt</label>
    <%= form.text_field :city, id: :anschreiben_city, placeholder: 'Berlin' %>
  </div>

   <div class="field">
    <label>Datum</label>
    <%= form.date_select :datum, id: :anschreiben_datum, placeholder: '12.12.2021' %>
  </div>
  <div class="field">
    <label>Unternehme Name:</label>
    <%= form.text_field :company_name, id: :anschreiben_company_name, placeholder: 'BMW, Lidl, etc..' %>
  </div>
  </div>
  <div class="column">
  <div class="field">
    <label>Unternehme Adress</label>
    <%= form.text_field :comapay_adress, id: :anschreiben_comapay_adress, placeholder: 'Haut str 10' %>
  </div>

 <div class="field">
   <label>PLZ</label>
    <%= form.text_field :plzz, id: :anschreiben_plzz, placeholder: '13404 etc'%>
  </div>
  <div class="field">
    <label>Unternehme Stadt</label>
    <%= form.text_field :company_city, id: :anschreiben_company_city, placeholder: 'Berlin ' %>
  </div>

  <div class="field">
    <label>Bewerbung als </label>
    <%= form.text_field :bewerbung, id: :anschreiben_bewerbung, placeholder: 'Empfangsmitarbiter, Verkäuferin' %>
  </div>

  <div class="field">
    <label>Stelle</label>
    <%= form.text_field :stelle, id: :anschreiben_stelle, placeholder: 'Empfangsmitarbiter, Verkäuferin' %>
  </div>
</div>
</div>
  <div class="actions">
    <%= form.submit 'Erstellen' %>
  </div>
<% end %>

app/views/anschreibens/edit.html.erb
<h1>Editing Anschreiben</h1>

<%= render 'form', anschreiben: @anschreiben %>

<%= link_to 'Show', @anschreiben %> |
<%= link_to 'Back', anschreibens_path %>

app/views/anschreibens/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Anschreibens</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Adess</th>
      <th>Plz</th>
      <th>City</th>
      <th>Company name</th>
      <th>Comapay adress</th>
      <th>Company city</th>
      <th>Bewerbung</th>
      <th>Stelle</th>
      <th>Datum</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @anschreibens.each do |anschreiben| %>
      <tr>
        <td><%= anschreiben.name %></td>
        <td><%= anschreiben.adess %></td>
        <td><%= anschreiben.plz %></td>
        <td><%= anschreiben.city %></td>
        <td><%= anschreiben.company_name %></td>
        <td><%= anschreiben.comapay_adress %></td>
        <td><%= anschreiben.company_city %></td>
        <td><%= anschreiben.bewerbung %></td>
        <td><%= anschreiben.stelle %></td>
        <td><%= anschreiben.datum %></td>
        <td><%= link_to 'Show', anschreiben %></td>
        <td><%= link_to 'Edit', edit_anschreiben_path(anschreiben) %></td>
        <td><%= link_to 'Destroy', anschreiben, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Anschreiben', new_anschreiben_path %>

app/views/anschreibens/new.html.erb
<%= render 'form', anschreiben: @anschreiben %>

<%#= link_to 'Back', anschreibens_path %>

app/views/anschreibens/show.html.erb
<style>
  .column-ans {
    width: 90%;
    height: auto;
    position: relative;
    border: 0.4px solid black;
    padding: 20px;
}

  h3 {
    text-align: left;
    font-size: 14px;
  }
  .div p {
    text-align: left;
    font-size: 15px;
    padding: 0 40% ;
    margin: 2px 2px;
    color: black;
  }
  .div-left h2 {
    text-align: left;
    font-size: 15px;
    padding: 0 0 ;
    margin: 0 0;
  }
  #title{
    text-align: center;
  }
  strong {
    color: blue;
  }
  .content p {
    color: black;
  }
</style>
<div class="row">
  <div class="column-ans">
<div class="div">
<p>
  <%= @anschreiben.name %>
</p>
<p>
  <%= @anschreiben.adess %>
</p>
<p><%= @anschreiben.plz %> <%= @anschreiben.city %></p>
</div><br>
<div class="div-left">
<h2>
  <%= @anschreiben.company_name %>
</h2>

<h2>
  <%= @anschreiben.comapay_adress %>
</h2>

<h2>
  <%= @anschreiben.plzz %> <%= @anschreiben.company_city %>
</h2>
</div>
<div class="bewerbung-title">
  <h2 id="title">  Bewerbung als  <%= @anschreiben.bewerbung %> </h2>
</div><br><br>
<div class="content">
  <p>Sehr geehrte Damen und Herren, </p>
  <p>Mit großem Interesse habe ich Ihre Anzeige gelesen und möchte mich hiermit auf die ausgeschriebene Stelle als <%= @anschreiben.stelle %>  bewerben</p>
  <p>
Sie suchen eine lösungsorientierte und kommunikative Vertrieblerin, für die
Stressresistenz, Organisationstalent, Flexibilität und Kundengespür nicht nur leere
Worthülsen sind, sondern Praxisalltag? Dann stelle ich mich Ihnen gerne vor.
Mein Sales Management Studium an der Musterhochschule werde ich im Juni mit dem
Bachelorabschluss (voraussichtliche Note 1,4) beenden. Seit mehr als zwei Jahren bin
ich als Werkstudentin in der Musterfirma GmbH tätig und bin bereits intensiv in die
Koordination der Vertriebsmitarbeiter und <strong><%= @anschreiben.bewerbung %></strong> die Abwicklung im Vertriebsinnendienst
eingebunden. Nun suche ich ein Unternehmen, in dem ich mein erlerntes Wissen
einbringen sowie ausbauen kann. Dabei ist mir Ihr Unternehmen besonders im Kopf
geblieben, da ich mich vollkommen mit den innovativen Verkaufsstrategien Ihres
Unternehmens identifizieren kann.
Es bereitet mir viel Freude, meine Kommunikationsstärke und meine
betriebswirtschaftlichen Kenntnisse zu verbinden und gewinnbringend einzusetzen.
Besonders die Akquise neuer Kunden und die Betreuung bestehender Kunden motiviert
mich. Durch meine Tätigkeit als Werkstudentin habe ich gelernt, mit stressigen
Situationen umzugehen, in diesen die Ruhe zu bewahren und dabei termingerecht gute
Arbeit abzuliefern.
Voller Elan stehe ich Ihnen für eine Anstellung ab dem 01.07.2020 zur Verfügung. Ich
bedanke mich für die Berücksichtigung meiner Bewerbungsunterlagen und freue mich
sehr darauf, Sie in einem persönlichen Gespräch von meinen Fähigkeiten zu
überzeugen.
  </p>
  <p>
  <%= @anschreiben.datum %>
</p>
<p>Mit freundlichen Grüßen</p>
<p> <%= @anschreiben.name %></p>
</div>
  </div>
</div>
<%= link_to 'Edit', edit_anschreiben_path(@anschreiben) %> |
<%= link_to 'Back', anschreibens_path %>