config/routes.rb
Rails.application.routes.draw do
  resources :trainings
  resources :anschreibens
  resources :lebenslaufs
  resources :jobs
  resources :cvs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'jobs#index'
  get 'about', to: 'welcome#about'

  resources :articles

  get 'signup', to: "users#new"
  resources :users, except: [:new]
  get 'login', to: "sessions#new"
  post 'login', to: "sessions#create"
  delete 'logout', to: "sessions#destroy"

  resources :categories, except: [:destroy]
end

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%="#{name}" %>'>
        <a href="#" class="close" data-dismiss="alert">
          &#215;
        </a>
        <%= msg %>
      </div>
    <% end %>  
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Traum Jobs Berlin", root_path, class: "navbar-brand", id: "logo" %>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
         <li><%#= link_to 'Post Job', new_job_path %></li>
         <li><%#= link_to 'Jobs', jobs_path %></li>
         <li><%= link_to '   Cv / English', new_cv_path %></li>
         <li><%= link_to 'Lebenslauf / Deutsch', new_lebenslauf_path %></li>

         <li><%= link_to ' Vorstellungs Training', trainings_path %></li>
            <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Bewerbungs <span class="caret"></span></a>
            <ul class="dropdown-menu">
            <li><%= link_to 'Lebenslauf / Deutsch', new_lebenslauf_path %></li>
             <li><%= link_to 'Anschreiben', new_anschreiben_path %></li>
             <li><%= link_to 'New Vorstellungs Training', new_training_path %></li>
            </ul>
          </li>

        <% if logged_in? && current_user.admin? %>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= "Admin Dashboard" if current_user.admin? %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
             <li><%= link_to 'Post Job', new_job_path %></li>
            </ul>
          </li>
          <% end %>
        </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>

          <li><%= link_to "Log out", logout_path, method: :delete %></li>

              <li><%#= link_to "Edit your profile", edit_user_path(current_user) %></li>
              <li><%#= link_to "View your profile", user_path(current_user) %></li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
          <li><%= link_to "Sign up", signup_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CvMaker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <%#= debug(params) if Rails.env.development? %>

  </body>
</html>

app/views/layouts/pdf.html.erb
<!doctype html>
<html>
  <head>
    <meta charset='utf-8' />
    <%= wicked_pdf_stylesheet_link_tag "pdf" -%>
    <%= wicked_pdf_javascript_include_tag "number_pages" %>
    <%= wicked_pdf_stylesheet_link_tag "lebenslauf.scss" -%>
<%= wicked_pdf_stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
<%= wicked_pdf_javascript_include_tag "application", "data-turbolinks-track" => true %>

<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<script src="//code.jquery.com/ui/1.11.2/jquery-ui.js"></script>
  </head>
  <body onload='number_pages'>
    <div id="header">
            <%#= wicked_pdf_image_tag(@lebenslauf:avatar)%>

    </div>
    <div id="content">
      <%= yield %>
    </div>
  </body>
</html>